os: osx
osx_image: xcode9.1
language: c
compiler: clang
env:
  - TASK=check CONFIG_FLAGS="--enable-Werror --enable-test-Werror"
script:
  - autoreconf -iv
  - ./configure $CONFIG_FLAGS
  - make $TASK
after_failure:
  - find . -name test-suite.log -exec tail -n +1 {} +
